
apiVersion: apps/v1
kind: Deployment
metadata:
  name: colors-app
  labels:
     app: colors

spec:
  replicas: 2
  selector:
    matchLabels:
      app: colors

  template:
    metadata:
      labels:
        app: colors
    spec:
      containers:
      - name: colors
        image: aprazors/colors
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
